name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      target:
        description: 'Deploy target'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH for Build
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🔧 Build Docker Image on Remote Server
        run: |
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              BRANCH="${{ github.head_ref }}"
            else
              BRANCH="${{ github.ref_name }}"
            fi

            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              TARGET="${{ github.event.inputs.target }}"
            elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
              TARGET="stage"
            elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
              TARGET="prod"
            else
              echo "❌ Cannot determine deployment target"
              exit 1
            fi

            echo "ℹ️ Building for target: $TARGET, branch: $BRANCH"

            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
              export BRANCH="$BRANCH"
              cd ~/projects/quakke-backend/scripts
              if [[ "$TARGET" == "stage" ]]; then
                bash build-stage.sh
              else
                bash build-prod.sh
              fi
            EOF

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 📦 Deploy Docker Container to Remote Server
        run: |
          TARGET="${{ github.event.inputs.target }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd ~/projects/quakke-backend/scripts
            if [[ "$TARGET" == "stage" ]]; then
              bash deploy-stage.sh
            else
              bash deploy-prod.sh
            fi
          EOF

  cleanup:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🧹 Cleanup Docker Resources on Remote Server
        run: |
          TARGET="${{ github.event.inputs.target }}"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd ~/projects/quakke-backend/scripts
            if [[ "$TARGET" == "stage" ]]; then
              bash cleanup-stage.sh
            else
              bash cleanup-prod.sh
            fi
          EOF
